# Generated by Django 4.2.6 on 2023-11-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontent1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopost',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='イメージ１'),
        ),
    ]
